services:
  - type: web
    name: boardgameplanner-demo
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: demo
